// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// armaCrossprod
SEXP armaCrossprod(arma::mat A, arma::mat B);
RcppExport SEXP _hdm_armaCrossprod(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(armaCrossprod(A, B));
    return rcpp_result_gen;
END_RCPP
}
// fastLassoShooting
List fastLassoShooting(const arma::mat& XX2, const arma::colvec& Xy2, arma::colvec& beta_start, const arma::colvec& lambda, const int max_iter, const double optTol);
RcppExport SEXP _hdm_fastLassoShooting(SEXP XX2SEXP, SEXP Xy2SEXP, SEXP beta_startSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP optTolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type XX2(XX2SEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Xy2(Xy2SEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type beta_start(beta_startSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type optTol(optTolSEXP);
    rcpp_result_gen = Rcpp::wrap(fastLassoShooting(XX2, Xy2, beta_start, lambda, max_iter, optTol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hdm_armaCrossprod", (DL_FUNC) &_hdm_armaCrossprod, 2},
    {"_hdm_fastLassoShooting", (DL_FUNC) &_hdm_fastLassoShooting, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_hdm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
