# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armaCrossprod <- function(A, B) {
    .Call('_hdm_armaCrossprod', PACKAGE = 'hdm', A, B)
}

fastLassoShooting <- function(XX2, Xy2, beta_start, lambda, max_iter, optTol) {
    .Call('_hdm_fastLassoShooting', PACKAGE = 'hdm', XX2, Xy2, beta_start, lambda, max_iter, optTol)
}

